In [1]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department

        Employee.employee_count += 1

    def average_salary(self, *salaries):
        total_salary = sum(salaries, self.salary)
        average_salary = total_salary / (len(salaries) + 1)
        return average_salary


class FulltimeEmployee(Employee):

    def __init__(self, name, family, salary, department, fulltime_property):
        super().__init__(name, family, salary, department)

        self.fulltime_property = fulltime_property


employee1 = Employee("Yasaswini Majety", "Family1", 50000, "Finance Department")
employee2 = FulltimeEmployee("Sindhu Majety", "Family2", 60000, "IT Delivery", "Fulltime Property")

average_salary_employee1 = employee1.average_salary(55000, 60000)
average_salary_employee2 = employee2.average_salary(65000, 70000)

print(f"Average Salary for {employee1.name}: ${average_salary_employee1:.2f}")
print(f"Average Salary for {employee2.name}: ${average_salary_employee2:.2f}")
print(f"Total Number of Employees: {Employee.employee_count}")

Average Salary for Yasaswini Majety: $55000.00
Average Salary for Sindhu Majety: $65000.00
Total Number of Employees: 2


In [2]:
import numpy as np

random_vector = np.random.uniform(1, 20, 20)

reshaped_array = random_vector.reshape(4, 5)

reshaped_array[np.arange(len(reshaped_array)), reshaped_array.argmax(axis=1)] = 0

print("Original array:")
print(random_vector)
print("\nReshaped array:")
print(reshaped_array)

Original array:
[ 2.38488052 17.12746892  0.          2.20820267 15.91806307  4.57622944
  0.          7.00238789  5.80459462  6.54141499  0.          7.91191417
 16.53174484  1.05726118  7.7310878   0.          9.25510301 12.38232492
  3.1325486   7.39587181]

Reshaped array:
[[ 2.38488052 17.12746892  0.          2.20820267 15.91806307]
 [ 4.57622944  0.          7.00238789  5.80459462  6.54141499]
 [ 0.          7.91191417 16.53174484  1.05726118  7.7310878 ]
 [ 0.          9.25510301 12.38232492  3.1325486   7.39587181]]
